# Generated by Django 5.0.1 on 2024-01-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contactus_phone_alter_contactus_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactModel',
        ),
    ]
